# fly.toml app configuration file generated for olakino on 2023-07-17T23:20:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "olakino"
primary_region = "bos"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
